// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw2_Student.Models;

#nullable disable

namespace cw2_Student.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250918144131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("cw2_Student.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataUrodzenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataUrodzenia = new DateOnly(2004, 6, 15),
                            Name = "Uczen1"
                        },
                        new
                        {
                            Id = 2,
                            DataUrodzenia = new DateOnly(2005, 7, 16),
                            Name = "Uczen2"
                        },
                        new
                        {
                            Id = 3,
                            DataUrodzenia = new DateOnly(2006, 8, 17),
                            Name = "Uczen3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
