// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw1_ef_sqlite.Models;

#nullable disable

namespace cw1_ef_sqlite.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20250908073238_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("cw1_ef_sqlite.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author A",
                            Title = "Book One",
                            Year = 2001
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author B",
                            Title = "Book Two",
                            Year = 2002
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author C",
                            Title = "Book Three",
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
